export const DEFAULT_SETTINGS = {
  theme: "lime",
  themeMode: "dark", // 'dark' | 'light' | 'amoled'
  restDuration: 90,
  weightUnit: "kg",
  weightIncrement: 2.5,
  weeklyGoal: 4,
  defaultSets: 3,
  defaultReps: 12,
  defaultDuration: 30,
  gender: "male",
  enableRpeRir: false,
};

export const DEFAULT_ROUTINES = [
  {
    id: "default-push",
    name: "Empuje",
    emoji: "🔥",
    color: "#ef4444",
    exercises: [
      {
        id: "chest-1",
        name: "Press de Banca",
        muscle: "Pecho",
        type: "reps",
        targetSets: 4,
        targetReps: 10,
        targetWeight: 60,
      },
      {
        id: "shoulder-1",
        name: "Press Militar",
        muscle: "Hombro",
        type: "reps",
        targetSets: 3,
        targetReps: 12,
        targetWeight: 30,
      },
      {
        id: "tricep-1",
        name: "Extensión Tríceps Polea",
        muscle: "Tríceps",
        type: "reps",
        targetSets: 3,
        targetReps: 15,
        targetWeight: 20,
      },
    ],
  },
  {
    id: "default-pull",
    name: "Tirón",
    emoji: "⚡",
    color: "#3b82f6",
    exercises: [
      {
        id: "back-1",
        name: "Dominadas",
        muscle: "Espalda",
        type: "reps",
        targetSets: 4,
        targetReps: 8,
        targetWeight: 0,
      },
      {
        id: "back-2",
        name: "Remo con Barra",
        muscle: "Espalda",
        type: "reps",
        targetSets: 3,
        targetReps: 10,
        targetWeight: 50,
      },
      {
        id: "bicep-1",
        name: "Curl de Bíceps con Barra",
        muscle: "Bíceps",
        type: "reps",
        targetSets: 3,
        targetReps: 12,
        targetWeight: 25,
      },
    ],
  },
  {
    id: "default-legs",
    name: "Pierna",
    emoji: "🦵",
    color: "#06b6d4",
    exercises: [
      {
        id: "leg-1",
        name: "Sentadilla Libre",
        muscle: "Pierna",
        type: "reps",
        targetSets: 4,
        targetReps: 8,
        targetWeight: 80,
      },
      {
        id: "leg-2",
        name: "Prensa de Piernas",
        muscle: "Pierna",
        type: "reps",
        targetSets: 3,
        targetReps: 12,
        targetWeight: 120,
      },
      {
        id: "leg-7",
        name: "Elevación de Gemelos",
        muscle: "Pierna",
        type: "reps",
        targetSets: 4,
        targetReps: 15,
        targetWeight: 40,
      },
    ],
  },
];